/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AssistanceStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export type AssistanceType = { 'inspection' : null } |
  { 'emergency' : null } |
  { 'repairHelp' : null } |
  { 'consultation' : null };
export type EstimateStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'rejected' : null };
export interface MechanicAssistanceRequest {
  'id' : bigint,
  'status' : AssistanceStatus,
  'serviceType' : AssistanceType,
  'bookingId' : bigint,
  'user' : Principal,
  'timestamp' : Time,
  'details' : string,
}
export type RepairCategory = { 'brakeJob' : null } |
  { 'other' : string } |
  { 'oilChange' : null } |
  { 'coolingSystem' : null } |
  { 'engineMaintenance' : null } |
  { 'transmission' : null } |
  { 'suspension' : null } |
  { 'electrical' : null } |
  { 'diagnostics' : null };
export interface RepairCostEstimate {
  'id' : bigint,
  'status' : EstimateStatus,
  'vehicleInfo' : string,
  'partsCost' : bigint,
  'laborHours' : number,
  'user' : Principal,
  'hourlyRate' : bigint,
  'totalCost' : bigint,
  'repairType' : RepairCategory,
}
export type Role = { 'admin' : null } |
  { 'customer' : null } |
  { 'garageOwner' : null } |
  { 'mechanic' : null };
export type Time = bigint;
export interface ToolRecommendation {
  'tools' : Array<string>,
  'consumables' : Array<string>,
  'category' : RepairCategory,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'roles' : Array<Role>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAssistanceRequest' : ActorMethod<
    [bigint, AssistanceType, string],
    bigint
  >,
  'createRepairEstimate' : ActorMethod<
    [RepairCategory, string, bigint, number, bigint],
    bigint
  >,
  'getAllAssistanceRequests' : ActorMethod<
    [],
    Array<MechanicAssistanceRequest>
  >,
  'getAllToolRecommendations' : ActorMethod<[], Array<ToolRecommendation>>,
  'getAssistanceRequest' : ActorMethod<
    [bigint],
    [] | [MechanicAssistanceRequest]
  >,
  'getCallerAssistanceRequests' : ActorMethod<
    [],
    Array<MechanicAssistanceRequest>
  >,
  'getCallerRepairEstimates' : ActorMethod<[], Array<RepairCostEstimate>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getRepairEstimate' : ActorMethod<[bigint], [] | [RepairCostEstimate]>,
  'getToolRecommendation' : ActorMethod<
    [RepairCategory],
    [] | [ToolRecommendation]
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveToolRecommendation' : ActorMethod<
    [RepairCategory, Array<string>, Array<string>],
    undefined
  >,
  'updateAssistanceRequestStatus' : ActorMethod<
    [bigint, AssistanceStatus],
    undefined
  >,
  'updateEstimateStatus' : ActorMethod<[bigint, EstimateStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];