/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AssistanceType = IDL.Variant({
  'inspection' : IDL.Null,
  'emergency' : IDL.Null,
  'repairHelp' : IDL.Null,
  'consultation' : IDL.Null,
});
export const RepairCategory = IDL.Variant({
  'brakeJob' : IDL.Null,
  'other' : IDL.Text,
  'oilChange' : IDL.Null,
  'coolingSystem' : IDL.Null,
  'engineMaintenance' : IDL.Null,
  'transmission' : IDL.Null,
  'suspension' : IDL.Null,
  'electrical' : IDL.Null,
  'diagnostics' : IDL.Null,
});
export const AssistanceStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const Time = IDL.Int;
export const MechanicAssistanceRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : AssistanceStatus,
  'serviceType' : AssistanceType,
  'bookingId' : IDL.Nat,
  'user' : IDL.Principal,
  'timestamp' : Time,
  'details' : IDL.Text,
});
export const ToolRecommendation = IDL.Record({
  'tools' : IDL.Vec(IDL.Text),
  'consumables' : IDL.Vec(IDL.Text),
  'category' : RepairCategory,
});
export const EstimateStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'rejected' : IDL.Null,
});
export const RepairCostEstimate = IDL.Record({
  'id' : IDL.Nat,
  'status' : EstimateStatus,
  'vehicleInfo' : IDL.Text,
  'partsCost' : IDL.Nat,
  'laborHours' : IDL.Float64,
  'user' : IDL.Principal,
  'hourlyRate' : IDL.Nat,
  'totalCost' : IDL.Nat,
  'repairType' : RepairCategory,
});
export const Role = IDL.Variant({
  'admin' : IDL.Null,
  'customer' : IDL.Null,
  'garageOwner' : IDL.Null,
  'mechanic' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'roles' : IDL.Vec(Role),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAssistanceRequest' : IDL.Func(
      [IDL.Nat, AssistanceType, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createRepairEstimate' : IDL.Func(
      [RepairCategory, IDL.Text, IDL.Nat, IDL.Float64, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'getAllAssistanceRequests' : IDL.Func(
      [],
      [IDL.Vec(MechanicAssistanceRequest)],
      ['query'],
    ),
  'getAllToolRecommendations' : IDL.Func(
      [],
      [IDL.Vec(ToolRecommendation)],
      ['query'],
    ),
  'getAssistanceRequest' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(MechanicAssistanceRequest)],
      ['query'],
    ),
  'getCallerAssistanceRequests' : IDL.Func(
      [],
      [IDL.Vec(MechanicAssistanceRequest)],
      ['query'],
    ),
  'getCallerRepairEstimates' : IDL.Func(
      [],
      [IDL.Vec(RepairCostEstimate)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getRepairEstimate' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(RepairCostEstimate)],
      ['query'],
    ),
  'getToolRecommendation' : IDL.Func(
      [RepairCategory],
      [IDL.Opt(ToolRecommendation)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveToolRecommendation' : IDL.Func(
      [RepairCategory, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'updateAssistanceRequestStatus' : IDL.Func(
      [IDL.Nat, AssistanceStatus],
      [],
      [],
    ),
  'updateEstimateStatus' : IDL.Func([IDL.Nat, EstimateStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AssistanceType = IDL.Variant({
    'inspection' : IDL.Null,
    'emergency' : IDL.Null,
    'repairHelp' : IDL.Null,
    'consultation' : IDL.Null,
  });
  const RepairCategory = IDL.Variant({
    'brakeJob' : IDL.Null,
    'other' : IDL.Text,
    'oilChange' : IDL.Null,
    'coolingSystem' : IDL.Null,
    'engineMaintenance' : IDL.Null,
    'transmission' : IDL.Null,
    'suspension' : IDL.Null,
    'electrical' : IDL.Null,
    'diagnostics' : IDL.Null,
  });
  const AssistanceStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const Time = IDL.Int;
  const MechanicAssistanceRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : AssistanceStatus,
    'serviceType' : AssistanceType,
    'bookingId' : IDL.Nat,
    'user' : IDL.Principal,
    'timestamp' : Time,
    'details' : IDL.Text,
  });
  const ToolRecommendation = IDL.Record({
    'tools' : IDL.Vec(IDL.Text),
    'consumables' : IDL.Vec(IDL.Text),
    'category' : RepairCategory,
  });
  const EstimateStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const RepairCostEstimate = IDL.Record({
    'id' : IDL.Nat,
    'status' : EstimateStatus,
    'vehicleInfo' : IDL.Text,
    'partsCost' : IDL.Nat,
    'laborHours' : IDL.Float64,
    'user' : IDL.Principal,
    'hourlyRate' : IDL.Nat,
    'totalCost' : IDL.Nat,
    'repairType' : RepairCategory,
  });
  const Role = IDL.Variant({
    'admin' : IDL.Null,
    'customer' : IDL.Null,
    'garageOwner' : IDL.Null,
    'mechanic' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'roles' : IDL.Vec(Role),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAssistanceRequest' : IDL.Func(
        [IDL.Nat, AssistanceType, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createRepairEstimate' : IDL.Func(
        [RepairCategory, IDL.Text, IDL.Nat, IDL.Float64, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'getAllAssistanceRequests' : IDL.Func(
        [],
        [IDL.Vec(MechanicAssistanceRequest)],
        ['query'],
      ),
    'getAllToolRecommendations' : IDL.Func(
        [],
        [IDL.Vec(ToolRecommendation)],
        ['query'],
      ),
    'getAssistanceRequest' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(MechanicAssistanceRequest)],
        ['query'],
      ),
    'getCallerAssistanceRequests' : IDL.Func(
        [],
        [IDL.Vec(MechanicAssistanceRequest)],
        ['query'],
      ),
    'getCallerRepairEstimates' : IDL.Func(
        [],
        [IDL.Vec(RepairCostEstimate)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getRepairEstimate' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(RepairCostEstimate)],
        ['query'],
      ),
    'getToolRecommendation' : IDL.Func(
        [RepairCategory],
        [IDL.Opt(ToolRecommendation)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveToolRecommendation' : IDL.Func(
        [RepairCategory, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'updateAssistanceRequestStatus' : IDL.Func(
        [IDL.Nat, AssistanceStatus],
        [],
        [],
      ),
    'updateEstimateStatus' : IDL.Func([IDL.Nat, EstimateStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };