/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface MechanicAssistanceRequest {
    id: bigint;
    status: AssistanceStatus;
    serviceType: AssistanceType;
    bookingId: bigint;
    user: Principal;
    timestamp: Time;
    details: string;
    assignedMechanic?: Principal;
}
export interface ToolRecommendation {
    tools: Array<string>;
    consumables: Array<string>;
    category: RepairCategory;
}
export type RepairCategory = {
    __kind__: "brakeJob";
    brakeJob: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "oilChange";
    oilChange: null;
} | {
    __kind__: "coolingSystem";
    coolingSystem: null;
} | {
    __kind__: "engineMaintenance";
    engineMaintenance: null;
} | {
    __kind__: "transmission";
    transmission: null;
} | {
    __kind__: "suspension";
    suspension: null;
} | {
    __kind__: "electrical";
    electrical: null;
} | {
    __kind__: "diagnostics";
    diagnostics: null;
};
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface RepairCostEstimate {
    id: bigint;
    status: EstimateStatus;
    vehicleInfo: string;
    partsCost: bigint;
    laborHours: number;
    user: Principal;
    hourlyRate: bigint;
    totalCost: bigint;
    repairType: RepairCategory;
}
export interface UserProfile {
    name: string;
    email: string;
    roles: Array<Role>;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum AssistanceStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    rejected = "rejected",
    accepted = "accepted"
}
export enum AssistanceType {
    inspection = "inspection",
    emergency = "emergency",
    repairHelp = "repairHelp",
    consultation = "consultation"
}
export enum EstimateStatus {
    pending = "pending",
    completed = "completed",
    rejected = "rejected"
}
export enum Role {
    admin = "admin",
    customer = "customer",
    garageOwner = "garageOwner",
    mechanic = "mechanic"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acceptAssistanceRequest(requestId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAssistanceRequest(bookingId: bigint, serviceType: AssistanceType, details: string): Promise<bigint>;
    createRepairEstimate(repairType: RepairCategory, vehicleInfo: string, partsCost: bigint, laborHours: number, hourlyRate: bigint): Promise<bigint>;
    getAllAssistanceRequests(): Promise<Array<MechanicAssistanceRequest>>;
    getAllToolRecommendations(): Promise<Array<ToolRecommendation>>;
    getAssistanceRequest(requestId: bigint): Promise<MechanicAssistanceRequest | null>;
    getCallerAssistanceRequests(): Promise<Array<MechanicAssistanceRequest>>;
    getCallerRepairEstimates(): Promise<Array<RepairCostEstimate>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getRepairEstimate(estimateId: bigint): Promise<RepairCostEstimate | null>;
    getToolRecommendation(category: RepairCategory): Promise<ToolRecommendation | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveToolRecommendation(category: RepairCategory, tools: Array<string>, consumables: Array<string>): Promise<void>;
    updateAssistanceRequestStatus(requestId: bigint, status: AssistanceStatus): Promise<void>;
    updateEstimateStatus(estimateId: bigint, status: EstimateStatus): Promise<void>;
}
import type { AssistanceStatus as _AssistanceStatus, AssistanceType as _AssistanceType, EstimateStatus as _EstimateStatus, MechanicAssistanceRequest as _MechanicAssistanceRequest, RepairCategory as _RepairCategory, RepairCostEstimate as _RepairCostEstimate, Role as _Role, Time as _Time, ToolRecommendation as _ToolRecommendation, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acceptAssistanceRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptAssistanceRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptAssistanceRequest(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAssistanceRequest(arg0: bigint, arg1: AssistanceType, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createAssistanceRequest(arg0, to_candid_AssistanceType_n10(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAssistanceRequest(arg0, to_candid_AssistanceType_n10(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async createRepairEstimate(arg0: RepairCategory, arg1: string, arg2: bigint, arg3: number, arg4: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createRepairEstimate(to_candid_RepairCategory_n12(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRepairEstimate(to_candid_RepairCategory_n12(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async getAllAssistanceRequests(): Promise<Array<MechanicAssistanceRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAssistanceRequests();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAssistanceRequests();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllToolRecommendations(): Promise<Array<ToolRecommendation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllToolRecommendations();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllToolRecommendations();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAssistanceRequest(arg0: bigint): Promise<MechanicAssistanceRequest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssistanceRequest(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssistanceRequest(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerAssistanceRequests(): Promise<Array<MechanicAssistanceRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerAssistanceRequests();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerAssistanceRequests();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerRepairEstimates(): Promise<Array<RepairCostEstimate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerRepairEstimates();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerRepairEstimates();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRepairEstimate(arg0: bigint): Promise<RepairCostEstimate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRepairEstimate(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRepairEstimate(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getToolRecommendation(arg0: RepairCategory): Promise<ToolRecommendation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getToolRecommendation(to_candid_RepairCategory_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getToolRecommendation(to_candid_RepairCategory_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n43(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n43(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveToolRecommendation(arg0: RepairCategory, arg1: Array<string>, arg2: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveToolRecommendation(to_candid_RepairCategory_n12(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveToolRecommendation(to_candid_RepairCategory_n12(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async updateAssistanceRequestStatus(arg0: bigint, arg1: AssistanceStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAssistanceRequestStatus(arg0, to_candid_AssistanceStatus_n48(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAssistanceRequestStatus(arg0, to_candid_AssistanceStatus_n48(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateEstimateStatus(arg0: bigint, arg1: EstimateStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEstimateStatus(arg0, to_candid_EstimateStatus_n50(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEstimateStatus(arg0, to_candid_EstimateStatus_n50(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_AssistanceStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssistanceStatus): AssistanceStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_AssistanceType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssistanceType): AssistanceType {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_EstimateStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EstimateStatus): EstimateStatus {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_MechanicAssistanceRequest_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MechanicAssistanceRequest): MechanicAssistanceRequest {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_RepairCategory_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RepairCategory): RepairCategory {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_RepairCostEstimate_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RepairCostEstimate): RepairCostEstimate {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_ToolRecommendation_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ToolRecommendation): ToolRecommendation {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MechanicAssistanceRequest]): MechanicAssistanceRequest | null {
    return value.length === 0 ? null : from_candid_MechanicAssistanceRequest_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RepairCostEstimate]): RepairCostEstimate | null {
    return value.length === 0 ? null : from_candid_RepairCostEstimate_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ToolRecommendation]): ToolRecommendation | null {
    return value.length === 0 ? null : from_candid_ToolRecommendation_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _AssistanceStatus;
    serviceType: _AssistanceType;
    bookingId: bigint;
    user: Principal;
    timestamp: _Time;
    details: string;
    assignedMechanic: [] | [Principal];
}): {
    id: bigint;
    status: AssistanceStatus;
    serviceType: AssistanceType;
    bookingId: bigint;
    user: Principal;
    timestamp: Time;
    details: string;
    assignedMechanic?: Principal;
} {
    return {
        id: value.id,
        status: from_candid_AssistanceStatus_n17(_uploadFile, _downloadFile, value.status),
        serviceType: from_candid_AssistanceType_n19(_uploadFile, _downloadFile, value.serviceType),
        bookingId: value.bookingId,
        user: value.user,
        timestamp: value.timestamp,
        details: value.details,
        assignedMechanic: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.assignedMechanic))
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tools: Array<string>;
    consumables: Array<string>;
    category: _RepairCategory;
}): {
    tools: Array<string>;
    consumables: Array<string>;
    category: RepairCategory;
} {
    return {
        tools: value.tools,
        consumables: value.consumables,
        category: from_candid_RepairCategory_n25(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _EstimateStatus;
    vehicleInfo: string;
    partsCost: bigint;
    laborHours: number;
    user: Principal;
    hourlyRate: bigint;
    totalCost: bigint;
    repairType: _RepairCategory;
}): {
    id: bigint;
    status: EstimateStatus;
    vehicleInfo: string;
    partsCost: bigint;
    laborHours: number;
    user: Principal;
    hourlyRate: bigint;
    totalCost: bigint;
    repairType: RepairCategory;
} {
    return {
        id: value.id,
        status: from_candid_EstimateStatus_n31(_uploadFile, _downloadFile, value.status),
        vehicleInfo: value.vehicleInfo,
        partsCost: value.partsCost,
        laborHours: value.laborHours,
        user: value.user,
        hourlyRate: value.hourlyRate,
        totalCost: value.totalCost,
        repairType: from_candid_RepairCategory_n25(_uploadFile, _downloadFile, value.repairType)
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    roles: Array<_Role>;
}): {
    name: string;
    email: string;
    roles: Array<Role>;
} {
    return {
        name: value.name,
        email: value.email,
        roles: from_candid_vec_n36(_uploadFile, _downloadFile, value.roles)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    rejected: null;
} | {
    accepted: null;
}): AssistanceStatus {
    return "cancelled" in value ? AssistanceStatus.cancelled : "pending" in value ? AssistanceStatus.pending : "completed" in value ? AssistanceStatus.completed : "rejected" in value ? AssistanceStatus.rejected : "accepted" in value ? AssistanceStatus.accepted : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    inspection: null;
} | {
    emergency: null;
} | {
    repairHelp: null;
} | {
    consultation: null;
}): AssistanceType {
    return "inspection" in value ? AssistanceType.inspection : "emergency" in value ? AssistanceType.emergency : "repairHelp" in value ? AssistanceType.repairHelp : "consultation" in value ? AssistanceType.consultation : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    brakeJob: null;
} | {
    other: string;
} | {
    oilChange: null;
} | {
    coolingSystem: null;
} | {
    engineMaintenance: null;
} | {
    transmission: null;
} | {
    suspension: null;
} | {
    electrical: null;
} | {
    diagnostics: null;
}): {
    __kind__: "brakeJob";
    brakeJob: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "oilChange";
    oilChange: null;
} | {
    __kind__: "coolingSystem";
    coolingSystem: null;
} | {
    __kind__: "engineMaintenance";
    engineMaintenance: null;
} | {
    __kind__: "transmission";
    transmission: null;
} | {
    __kind__: "suspension";
    suspension: null;
} | {
    __kind__: "electrical";
    electrical: null;
} | {
    __kind__: "diagnostics";
    diagnostics: null;
} {
    return "brakeJob" in value ? {
        __kind__: "brakeJob",
        brakeJob: value.brakeJob
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "oilChange" in value ? {
        __kind__: "oilChange",
        oilChange: value.oilChange
    } : "coolingSystem" in value ? {
        __kind__: "coolingSystem",
        coolingSystem: value.coolingSystem
    } : "engineMaintenance" in value ? {
        __kind__: "engineMaintenance",
        engineMaintenance: value.engineMaintenance
    } : "transmission" in value ? {
        __kind__: "transmission",
        transmission: value.transmission
    } : "suspension" in value ? {
        __kind__: "suspension",
        suspension: value.suspension
    } : "electrical" in value ? {
        __kind__: "electrical",
        electrical: value.electrical
    } : "diagnostics" in value ? {
        __kind__: "diagnostics",
        diagnostics: value.diagnostics
    } : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    rejected: null;
}): EstimateStatus {
    return "pending" in value ? EstimateStatus.pending : "completed" in value ? EstimateStatus.completed : "rejected" in value ? EstimateStatus.rejected : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    customer: null;
} | {
    garageOwner: null;
} | {
    mechanic: null;
}): Role {
    return "admin" in value ? Role.admin : "customer" in value ? Role.customer : "garageOwner" in value ? Role.garageOwner : "mechanic" in value ? Role.mechanic : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MechanicAssistanceRequest>): Array<MechanicAssistanceRequest> {
    return value.map((x)=>from_candid_MechanicAssistanceRequest_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ToolRecommendation>): Array<ToolRecommendation> {
    return value.map((x)=>from_candid_ToolRecommendation_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RepairCostEstimate>): Array<RepairCostEstimate> {
    return value.map((x)=>from_candid_RepairCostEstimate_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Role>): Array<Role> {
    return value.map((x)=>from_candid_Role_n37(_uploadFile, _downloadFile, x));
}
function to_candid_AssistanceStatus_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssistanceStatus): _AssistanceStatus {
    return to_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function to_candid_AssistanceType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssistanceType): _AssistanceType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_EstimateStatus_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EstimateStatus): _EstimateStatus {
    return to_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function to_candid_RepairCategory_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RepairCategory): _RepairCategory {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n44(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    roles: Array<Role>;
}): {
    name: string;
    email: string;
    roles: Array<_Role>;
} {
    return {
        name: value.name,
        email: value.email,
        roles: to_candid_vec_n45(_uploadFile, _downloadFile, value.roles)
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssistanceType): {
    inspection: null;
} | {
    emergency: null;
} | {
    repairHelp: null;
} | {
    consultation: null;
} {
    return value == AssistanceType.inspection ? {
        inspection: null
    } : value == AssistanceType.emergency ? {
        emergency: null
    } : value == AssistanceType.repairHelp ? {
        repairHelp: null
    } : value == AssistanceType.consultation ? {
        consultation: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "brakeJob";
    brakeJob: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "oilChange";
    oilChange: null;
} | {
    __kind__: "coolingSystem";
    coolingSystem: null;
} | {
    __kind__: "engineMaintenance";
    engineMaintenance: null;
} | {
    __kind__: "transmission";
    transmission: null;
} | {
    __kind__: "suspension";
    suspension: null;
} | {
    __kind__: "electrical";
    electrical: null;
} | {
    __kind__: "diagnostics";
    diagnostics: null;
}): {
    brakeJob: null;
} | {
    other: string;
} | {
    oilChange: null;
} | {
    coolingSystem: null;
} | {
    engineMaintenance: null;
} | {
    transmission: null;
} | {
    suspension: null;
} | {
    electrical: null;
} | {
    diagnostics: null;
} {
    return value.__kind__ === "brakeJob" ? {
        brakeJob: value.brakeJob
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "oilChange" ? {
        oilChange: value.oilChange
    } : value.__kind__ === "coolingSystem" ? {
        coolingSystem: value.coolingSystem
    } : value.__kind__ === "engineMaintenance" ? {
        engineMaintenance: value.engineMaintenance
    } : value.__kind__ === "transmission" ? {
        transmission: value.transmission
    } : value.__kind__ === "suspension" ? {
        suspension: value.suspension
    } : value.__kind__ === "electrical" ? {
        electrical: value.electrical
    } : value.__kind__ === "diagnostics" ? {
        diagnostics: value.diagnostics
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    admin: null;
} | {
    customer: null;
} | {
    garageOwner: null;
} | {
    mechanic: null;
} {
    return value == Role.admin ? {
        admin: null
    } : value == Role.customer ? {
        customer: null
    } : value == Role.garageOwner ? {
        garageOwner: null
    } : value == Role.mechanic ? {
        mechanic: null
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssistanceStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    rejected: null;
} | {
    accepted: null;
} {
    return value == AssistanceStatus.cancelled ? {
        cancelled: null
    } : value == AssistanceStatus.pending ? {
        pending: null
    } : value == AssistanceStatus.completed ? {
        completed: null
    } : value == AssistanceStatus.rejected ? {
        rejected: null
    } : value == AssistanceStatus.accepted ? {
        accepted: null
    } : value;
}
function to_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EstimateStatus): {
    pending: null;
} | {
    completed: null;
} | {
    rejected: null;
} {
    return value == EstimateStatus.pending ? {
        pending: null
    } : value == EstimateStatus.completed ? {
        completed: null
    } : value == EstimateStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Role>): Array<_Role> {
    return value.map((x)=>to_candid_Role_n46(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
